# Change these first
owner: Limbo-Studios # Your GitHub organization or username, where this repository lives
repo: limbo-status-page # The name of this repository

sites:
  - name: Limbo Yggdrasil Multiplayer Session Service
    url: https://auth.lsmp.site/api/yggdrasil/sessionserver
    expectedStatusCodes:
      - 404
  - name: Limbo Yggdrasil Authserver
    url: https://auth.lsmp.site/api/yggdrasil
    expectedStatusCodes:
      - 200
  - name: Mojang Multiplayer Session Service
    url: http://session.minecraft.net
    expectedStatusCodes:
      - 404
  - name: Limbo Auth Proxy
    url: https://authproxy.lsmp.site/auth
    expectedStatusCodes:
      - 503
  - name: Skins
    url: https://auth.lsmp.site/texture
    expectedStatusCodes:
      - 405
  - name: Limbo Yggdrasil Public API
    url: https://auth.lsmp.site/api/yggdrasil
  - name: Main LimboAuth Website
    url: https://auth.lsmp.site/
    expectedStatusCodes:
      - 200
      - 200
  - name: Limbo Yggdrasil
    url: https://auth.lsmp.site/api/yggdrasil/sessionserver/session/minecraft/profile
    expectedStatusCodes:
      - 404

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /limbo-status-page
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Limbo Services Status Page
  introTitle: "This page is used by Limbo Launcher to get LimboAuth Yggdrasil status."
  introMessage: We are not Mojang/Microsoft
  navbar:
    - title: Home
      href: /limbo-status-page
    - title: Limbo Launcher source code
      href: https://github.com/Limbo-Studios/LimboLauncher

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
